version: "3"

services:
  db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    image: fantastic-sport
    ports:
      - 8080:8080
      - 5005:5005
    links:
      - db
